### PR TITLE
Update to SpecialSource 1.8.2

### PR DESCRIPTION
**Pull request by Pokechu22**
Mainly for md-5/SpecialSource#50.

### CODE REVIEW

**Comment by LexManos** [comment]
I'll wait till he pushes a version bump, so we dont run into issues again where hes updated and broken things. Move away from the snapshot pulling.

**Comment by Pokechu22** [comment]
Fair enough.  FYI there already has been a version bump for 1.8.1, but that doesn't include these changes.

**Comment by LexManos** [comment]
Ya, I saw, we were using the snapshot because there were breaking changes we needed, or more specifically he fixed a bug that was breaking peoples things. Like I said, i'll wait till the next stable so we can fully test it.

**Comment by Pokechu22** [comment]
SpecialSource 1.8.2 has been released; I've updated this PR to use that rather than the snapshot.

**Pull request merged**
