### PR TITLE
Add mkdocs again and update for ForgeGradle 2.2

### PR DESCRIPTION
**Pull request by vinyldarkscratch**

### CODE REVIEW

**Comment by killjoy1221** [comment]
You should recommend the [shadow plugin](http://imperceptiblethoughts.com/shadow/) instead for shading.

**Comment by vinyldarkscratch** [comment]
@killjoy1221 I've never heard of that plugin until just now, but it looks interesting, I'll have to dig into it more!  If you were to write the appropriate changes for that plugin, I'd be more than happy to merge it into my own fork so our changes are together in the same PR.  🙂

**Comment by killjoy1221** [comment]
It's OK to keep the current documentation, but suggest using that plugin instead.

**Comment by LexManos** [comment]
Documents should go in the Documentation repo.

**Comment by vinyldarkscratch** [comment]
Ah, didn't know that there was a separate repo for that!  Will forward my contributions over there when I can.  😉

**Comment by kashike** [comment]
I don't see why ForgeGradle documentation would go in the MInecraftForge documentation repository.. they're separate projects, and the documentation is unrelated.

**Comment by LexManos** [comment]
Its the same org. It all goes in one place.

**Pull request closed without merging**
