### PR TITLE
Add check for compatible Gradle version range.

### PR DESCRIPTION
**Pull request by gigaherz**

### CODE REVIEW

**Comment by LexManos** [comment]
Have you tried pulling in a dynamic AF version based on the gradle version? If we can get that working we can expand the range. As it should only be AF that's the issue between versions.

**Comment by gigaherz** [comment]
Oh right you did mention that. I'm not sure it's possible to pick different dependency versions for the buildscript, but I'll try.

**Comment by LexManos** [comment]
Well it wouldnt be a different build script, it would be dynamically pulling in and loading the library.

**Comment by covers1624** [comment]
Can you rebase this onto the `FG_4` branch and force Gradle 6.8+.

**Comment by sciwhiz12** [comment]
The feature added by this PR is already implemented and merged in by #754.

**Pull request closed without merging**
