### PR TITLE
[WIP] Add a pack configuration where all artifacts will be packed into the …

### PR DESCRIPTION
**Pull request by matthewprenger**
…jar and the appropriate manifest entry will be created.

Forge/FML Feature: https://github.com/MinecraftForge/MinecraftForge/commit/dc4dc55dcdcb86ec800f2a9170e468673046685b

### CODE REVIEW

**Comment by AbrarSyed** [comment]
this is fine for other deps, but requires more if it is also allowed for mod dependencies or mod API dependencies. @cpw is that planned?

**Comment by killjoy1221** [comment]
How will this handle obfuscation? Project deps?

**Comment by Lunatrius** [comment]
The current implementation has a potential problem. When two mods ship different versions of the same dependency FML won't load up (duplicate mod screen etc).

**Comment by matthewprenger** [comment]
@Lunatrius Yeah thats why I stuck the WIP tag on it for now and put it on the back burner. @cpw mentioned he wanted to add an optional semver flag to Mods/Apis so FML could choose the more up to date dep to load.

**Pull request closed without merging**
