### PR TITLE
Changed getAllJava to getAllSource

### PR DESCRIPTION
**Pull request by BrainStone**
This is the way gradle compile java files by default.

### CODE REVIEW

**Comment by LexManos** [comment]
Retromapping only supports java so we can only pull in java code....

**Comment by AbrarSyed** [comment]
got the wrong spot you did...
https://github.com/MinecraftForge/ForgeGradle/blob/FG_2.2/src/main/java/net/minecraftforge/gradle/user/UserBasePlugin.java#L559

**Comment by BrainStone** [comment]
So now it should be the right spot

**Comment by DaemonUmbra** [comment]
Closing this PR as it does not target the currently supported ForgeGradle branch (``FG_3.0``).

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)

**Pull request closed without merging**
