### PR TITLE
Close Jar files after use

### PR DESCRIPTION
**Pull request by nallar**
Sorry about #447.

This PR includes the previous one, tests for most of the tasks with changes, and fixs for bugs introduced in the binpatch task and the fernflower artifact saver.

I've manually tested the MDK and TickProfiler with dev and decomp workspaces with these changes.

The remaining changed tasks which don't have tests are download tasks. I'm not sure how best to test them.

### CODE REVIEW

**Comment by nallar** [comment]
The latest SpecialSource version fails to remap some things. This causes `java.lang.NoSuchFieldError: x at net.minecraft.client.gui.GuiTextField.<init>(SourceFile:50)` with runClient on a non-decomp workspace.

Haven't yet got an mcve of the issue.

Latest test commit bundles a version of SpecialSource with the JarFile changes but without the java 9 support and without ASM 6. This doesn't have the remapping bug.

**Comment by nallar** [comment]
Confirmed the source of the remapping issue as a bug in SpecialSource, see md-5/SpecialSource/issues/47.

**Comment by nallar** [comment]
@mezz Should be ready to go now.

Can you confirm this still solves your original problem with multi-project builds and JVM crashes?

**Comment by mezz** [comment]
Tested with Binnie's and it built successfully.

**Comment by Barteks2x** [comment]
This could explain why when using gradle daemon I had to kill the daemon before running gradle clean when on windows (otherwise it wasn't able to delete the jar files because they are still used by the daemon that tries to delete them).

**Comment by LexManos** [comment]
Lets try this again, mezz says its good to go..

**Pull request merged**
