### PR TITLE
Fix deprecation (Due to be removed in Gradle 6.0)

### PR DESCRIPTION
**Pull request by QartemisT**

### CODE REVIEW

**Comment by LexManos** [comment]
You're gunna need to be a lot more descriptive then this.
As for Gradle 6 compatibility, there are quite a few other things we need to test before we even think about moving twards that officially.

I would LOVE to get rid of our Artifactual hacks, but as it sits, even in Gradle 6 there doesn't seem to be anything that provides the functionality we need.

**Comment by loordgek** [comment]
https://docs.gradle.org/5.5/release-notes.html#transforming-dependency-artifacts-on-resolution
does this help ?

**Comment by LexManos** [comment]
Not in the slightest, we've already looked into that system and it is not functional for our needs.

**Comment by QartemisT** [comment]
Exact words from gradle's output:

```
The TaskContainer.remove(Object) method has been deprecated.
    This is scheduled to be removed in Gradle 6.0. Prefer disabling the task instead,
    see Task.setEnabled(boolean).
```

**Comment by covers1624** [comment]
This has been resolved in FG 4.

**Pull request closed without merging**
