### PR TITLE
Update SpecialSource and close SS Jar files after use

### PR DESCRIPTION
**Pull request by mezz**
This is a continuation of the work in this PR to SS https://github.com/md-5/SpecialSource/pull/44.

### CODE REVIEW

**Comment by mezz** [comment]
@nallar does this look good to you?
I tried running this against Binnie's to see if it fixed my issue here https://github.com/md-5/SpecialSource/issues/45 but it did not.

**Comment by nallar** [comment]
Looks good. That's a shame that it didn't help...

There are some more places which don't always call close or aren't using try/finally or don't call closeEntry, can you try with these changes?

https://github.com/nallar/ForgeGradle/commit/ed952f4caf4f35714b5592f9d18cb32d7816fac8

**Comment by mezz** [comment]
Thanks, but unfortunately the fixes in your commit still didn't fix my issue.
I wasn't able to try with the SS fixes since I couldn't figure out a way to properly build FG with it, the dependencies make it a bit complicated when it's not hosted on maven.

**Comment by nallar** [comment]
You can use:

```gradle
dependencies {
    compile files('libs/something_local.jar')
}
```

**Comment by mezz** [comment]
I tried that but I get a crash in objectweb since there seem to be conflicting versions working together.
ForgeGradle has a different version of `org.ow2.asm:asm-debug-all` than SS.
```
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:79)
	at org.objectweb.asm.commons.ClassRemapper.<init>(ClassRemapper.java:61)
	at org.objectweb.asm.commons.ClassRemapper.<init>(ClassRemapper.java:56)
	at net.md_5.specialsource.RemappingClassAdapter.<init>(RemappingClassAdapter.java:78)
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:248)
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:231)
	at net.md_5.specialsource.JarRemapper.remapJar(JarRemapper.java:189)
	at net.minecraftforge.gradle.user.TaskSingleReobf.applySpecialSource(TaskSingleReobf.java:234)
	at net.minecraftforge.gradle.user.TaskSingleReobf.doTask(TaskSingleReobf.java:191)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
```
It's checking that the api version is correct, but it's not so it crashes.
I guess I'll try stripping it out.

**Comment by nallar** [comment]
Change the dependency on asm in ForgeGradle to `compile 'org.ow2.asm:asm-debug-all:6.0_BETA'`

Another ForgeGradle change which may help: https://github.com/nallar/ForgeGradle/commit/b82a559a7e79ff844a79127bbe336ec65e3f26d6

**Comment by mezz** [comment]
Ok got it to run, but it didn't fix my issue.

If I try with your latest FG change, I get a new crash(even on my local machine, which was working before). I think you may have a subtle bug
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':reobfJar'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: E:\code\Binnie1.12\build\classes\java\api (The system cannot find the path specified)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:57)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:711)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 27 more
Caused by: java.io.FileNotFoundException: E:\code\Binnie1.12\build\classes\java\api (The system cannot find the path specified)
	at net.md_5.specialsource.Jar.init(Jar.java:241)
	at net.minecraftforge.gradle.user.TaskSingleReobf.applySpecialSource(TaskSingleReobf.java:222)
	at net.minecraftforge.gradle.user.TaskSingleReobf.doTask(TaskSingleReobf.java:189)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	... 39 more
```

**Comment by nallar** [comment]
My bad.

Does this work? https://github.com/nallar/ForgeGradle/commit/4b038201c53c54a9fb9d08e0b5becafb72913944

If that doesn't help, `-Dsun.zip.disableMemoryMapping=true` may work as a workaround. Failing that, completely out of ideas.

:(

**Comment by mezz** [comment]
Looks good now, my build worked twice in a row.
Trying a 3rd to feel confident that it's really fixed.

**Comment by mezz** [comment]
It's working :)

**Comment by nallar** [comment]
Per @md-5 [here](https://github.com/md-5/SpecialSource/pull/46#discussion_r137510597) some of the changes I made were unnecessary. That was dumb. Will remove those tonight.

**Comment by nallar** [comment]
Simpler change here: d80af7740c2822e6896d361a9e

Can you confirm that this still works?

**Comment by mezz** [comment]
Confirmed that with your latest SS and FG changes, it still works.

**Comment by mezz** [comment]
@nallar can you make your PR to FG here to replace this one?

**Comment by nallar** [comment]
@mezz Done, #447.

**Comment by mezz** [comment]
Thanks @nallar!
Closing this in favor of the complete fix in #447.

**Pull request closed without merging**
