### PR TITLE
introduce Travis

### PR DESCRIPTION
**Pull request by hannesa2**
Additional you have to add `ForgeGradle` to your [Travis](https://travis-ci.org)

### CODE REVIEW

**Comment by hannesa2** [comment]
Ahh, I see you use Jenkins right now. But I can't see results.
I still prefer transparent Travis

**Comment by Unnoen** [comment]
The choice for Jenkins was made during the 1.13 rewrite, there's some private information in the builds such as publishing to maven and webhooks which is why it's not public, it may be in the future.

Unrelated, but I noticed your issue in the MinecraftForge repo earlier, if you want more information and discussion [our Discord server](https://discord.gg/UvedJ9m) would be better suited for that.

**Comment by hannesa2** [comment]
> it may be in the future.

Maybe the future is now ?

In Travis you can add some secret variables
image

which only the maintainer can see. This solves the problem about private information

**Comment by Unnoen** [comment]
Like I said, possibly in the future, we are always looking at improving things, especially the build pipeline, however it's not as simple as that right now.

**Pull request closed without merging**
