### PR TITLE
Add GlStateManager remapping, Needs to have import adding fixed

### PR DESCRIPTION
**Pull request by clienthax**

### CODE REVIEW

**Comment by GirafiStudios** [comment]
Yes please!

**Comment by AbrarSyed** [comment]
Please add a constant for the state manager import thing too. Feel free to rename the import check constant.

On August 31, 2015 10:32:24 AM PDT, clienthax <notifications@github.com> wrote:
>
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/MinecraftForge/ForgeGradle/pull/253
>
>-- Commit Summary --
>
>  * Add GlStateManager remapping, Needs to have import adding fixed
>
>-- File Changes --
>
>M src/main/java/net/minecraftforge/gradle/util/mcp/GLConstantFixer.java
>(5)
>   M src/main/resources/net/minecraftforge/gradle/util/mcp/gl.json (26)
>
>-- Patch Links --
>
>https://github.com/MinecraftForge/ForgeGradle/pull/253.patch
>https://github.com/MinecraftForge/ForgeGradle/pull/253.diff
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/MinecraftForge/ForgeGradle/pull/253

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by clienthax** [comment]
@AbrarSyed not really possible because of things in the package not needing to import it and things still use the base opengl calls in places, I'm honestly not sure what the best way is to complete the fix

**Comment by AbrarSyed** [comment]
Just requesting a constant instead of a literal there. Surely that's possible.

**Comment by AbrarSyed** [comment]
squash commits please

**Comment by LexManos** [comment]
This'll have to be a opt-in option so we don't break old patches.

**Comment by DaemonUmbra** [comment]
Closing this PR as it does not target the currently supported ForgeGradle branch (``FG_3.0``).

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)

**Pull request closed without merging**
