### PR TITLE
Ensure that the JDK version is within the supported range

### PR DESCRIPTION
**Pull request by gigaherz**
Minimum required is set to 1.8.0_52, up to but **not** including 11.0.

### CODE REVIEW

**Comment by ichttt** [comment]
Actually minimum is 101 as this is the first one that ships the LE certificates that forge file server uses

**Comment by gigaherz** [comment]
Oh! Lex mentioned 52, I guess neither of us thought of Let's Encrypt. Fixing.

**Comment by drekryan** [comment]
Actually the following commit fixed this in Forge so honestly a minimum of 52 (which MC ships with) is fine if I understand correctly. https://github.com/MinecraftForge/MinecraftForge/commit/d9c4446ccc0931ba1fdbbc5156c60740b97dea6e

**Comment by ichttt** [comment]
This is ForgeGradle not Forge itself. FG also needs to pull stuff from the files server. So no, it needs at least 101 to use https to forge maven

**Comment by bs2609** [comment]
To make things clear, the vanilla launcher downloads 8u**51**. A subversion of 52 does not correspond to any actual Java 8 release from Oracle (e.g. https://www.oracle.com/technetwork/java/javase/documentation/8u-relnotes-2225394.html).

**Comment by gigaherz** [comment]
Oh so it is u51.... could have sworn it was 52. 

Remember that you can still use u51 in your run/launch configs, separate from the gradle jdk, if you are in a situation where u51 is needed. It won't work for `gradlew runClient`, though, but that's a very minor annoyance.

In any case, if Lex prefers it, I can set it to 51 and try to make use of that FixSSL hack within ForgeGradle.

**Comment by LexManos** [comment]
i said 52 {meant 51} because Mojang ships 51. IF they get to this code. Then they have already gone past the LetsEncrypt issue. As they have downloaded the FG code.

**Pull request merged**
