### PR TITLE
Migrated to HTTPS support for Maven repo

### PR DESCRIPTION
**Pull request by JackCarterSmith**
Fix errors "501 HTTPS  required" when using gradle

#658

### CODE REVIEW

**Comment by DaemonUmbra** [comment]
FG1.2 is no longer being developed.
If you REALLY want to use 1.7.10, feel free to update the 1.7.10 ForgeDev workspace to use FG3.

**Comment by LexManos** [comment]
Note: This actually  WOULDN'T fix the error. As you'll notice the server throwing the error ISNT one of the ones you've changed. But yes, if you want any sense of being accepted. The only option is to put in the work to modernize the old branch to fg3.

**Comment by JackCarterSmith** [comment]
OK, no problem.
I'm still working on one of my mods in 1.7.10 when suddenly no longer possible to use gradle because of this error... You mean that it is possible to use FG-3 with MC 1.7.10?
If I'm not mistaken, https://files.minecraftforge.net/maven refers to http://repo1.maven.org/maven2/, hence the link with the issue #658

**Comment by DaemonUmbra** [comment]
It's possible, but a few required extra steps are yet to be taken and nobody has stepped up to do it.

**Comment by LexManos** [comment]
> If I'm not mistaken, https://files.minecraftforge.net/maven refers to http://repo1.maven.org/maven2/

You are mistaken, they are two completely different servers, that only show up in the stack trace because both are checked for the artifact.

And yes, it's possible to use literally any version of Minecraft {or any other java project} with FG3. Someone just needs to make the datasets needed. Nobdoy have bothered to because old versions are old and nobody cares.

**Pull request closed without merging**
