### PR TITLE
Fix for #347 and add support for description keys in litemod.json

### PR DESCRIPTION
**Pull request by Mumfrey**
Sorry it took a while, I've been super busy IRL for the last few weeks. This PR addresses the following:
- Provides the fix for issue #347, I have now had a chance to test this and verify that it does indeed solve the problem
- Adds support for `description` keys in the `litemod` task which were previously unsupported. It provides support for sub-mod descriptions by providing a custom `TypeAdapter` for the description map

### CODE REVIEW

**Comment by killjoy1221** [comment]
Can you also add support for adding arbitrary litemod entries?

**Comment by killjoy1221** [comment]
Can we get this merged soon?

**Comment by killjoy1221** [comment]
Also, this should probably be retargetted to FG_2.2 and/or FG_2.1

**Comment by Mumfrey** [comment]
Rebased this on 2.2 and tested thorougly. Any chance this can be merged now?

**Pull request merged**
