### PR TITLE
Fix incorrect coremod launch argument

### PR DESCRIPTION
**Pull request by simon816**
There should be an equals sign not a space.

Note: I have not tested this change, I only modified it from the GitHub web interface.

### CODE REVIEW

**Comment by Minecrell** [comment]
You need to change it above for the client too.

**Comment by simon816** [comment]
Oh yeah. Somehow didn't notice that

**Comment by AbrarSyed** [comment]
Just something you noticed? Or is this an actualy broken for the the corenod projects right now?

**Comment by simon816** [comment]
Noticed this when re-setting my Sponge workspace when it updated to FG 2.
Also this: https://forums.spongepowered.org/t/running-sponge-in-eclipse/9432

**Pull request merged**
