### PR TITLE
[FG_3.0] Complete refactoring of RunConfig setup.

### PR DESCRIPTION
**Pull request by OhYea777**
This is a result of various discussions for the best way to allow for multiple mods, from multiple source sets. What this allows you to do is specify an arbitrary number of run configs, with an arbitrary number of mods. All of which can be parents and children to be merged into themselves.

I wrote a overcomplicated example as a practical demonstration for what this will allow you to be able to do: [OhYea777/ForgeOCEP](https://github.com/OhYea777/ForgeOCEP).

I also wrote some documentation for the MDK, as part of my Forge PR MinecraftForge/MinecraftForge#5333, that implements these changes:

```gradle
// default run configurations.
// these can be tweaked, removed, or duplicated as needed.
runs {
    // Specifies the name of the run config. 'client' will extend from the userdevConfig's 'client' run config
    client {
        workingDirectory project.file('run').canonicalPath

        // Here you can specify a number of mods that are contained
        // within your project. This allows for having multiple mods,
        // from multiple source sets, loaded at runtime
        mods {
            // The name of the mod
            ExampleMod {
                // The source set for the mod
                source sourceSets.main

                // You can specify multiple source sets per mod
                // sources sourceSets.api, sourceSets.main

                // You can also specify additional resource directories to be added, for this given mod
                // resource project.file('some/resource/dir')
                
                // You can also specify arbitrary classes directories, for this given mod
                // NOTE: only 'classes' can be used and not 'class' due to it being a reserved keyword
                // classes project.file('some/classes/dir')
                
                // You can also overwrite all existing resource directories specified, this includes those in the
                // specified source sets
                // resources = project.file('only/this/resources/dir')
                
                // The same goes for classes
                // classes = project.file('only/this/classes/dir')
            }
        }
    }

    // You can specify any number of run configs
    // NOTE: only the run configs named 'client' and 'server' will extend from their userdevConfig's counterparts
    testClient {
        // You can specify a parent run to be merged into this run config
        // NOTE: it will not override anything set within this run config
        parent runs.client

        mods {
            // Because we are including the parent 'runs.client' config into this run config,
            // the mod 'ExampleMod' will be added

            // You can specify any number of mods
            ExampleModTest {
                source sourceSets.test
            }
        }
    }
    
    server {
        workingDirectory project.file('run').canonicalPath

        // You can specify any arguments you wish to pass to the launcher
        arg 'nogui'

        mods {
            ExampleMod {
                source sourceSets.main
            }
        }
    }

    testServer {
        parent runs.server

        mods {
            ExampleModTest {
                source sourceSets.test
            }
        }
    }
}
```

### CODE REVIEW

**Comment by OhYea777** [comment]
Oops, forgot to run `:updateLicenses` so it was failing to build

**Comment by OhYea777** [comment]
Updated to work with the current implementation for multi mod support in Forge. This _should_ also add backwards-compatibility with how run configs are currently set up

**Comment by OhYea777** [comment]
Fix conflicts

**Comment by OhYea777** [comment]
So, looking at MinecraftForge/MinecraftForge#5438 this adds a _kinda_ fix. Essentially it now generates the launch configs similar to the way that it does for IntelliJ, but using a new `:genEclipseRuns` task. Since Eclipse is painful, it actually has to generate 3 separate launch files based on a single run config. For example:

- `gradle_prepare_runClient.launch`
  - This is a launch config for running the preparation task for this run config. It actually also compiles the source sets that were specified
- `java_runClient.launch`
  - This is the launch config for actually running the java program, launching minecraft with the mods
- `runClient.launch`
  - This is a group launch config, it runs the above two launch configs in sequential order `gradle_prepare_runClient.launch` then `java_runClient.launch`

**Comment by OhYea777** [comment]
Okay, so after talks with @LexManos I've adjusted the `genEclipseRuns` task to set the **MOD_CLASSES** environment variable based off of the Eclipse output directories

**Comment by OhYea777** [comment]
This should fix MinecraftForge/MinecraftForge#5438

**Comment by OhYea777** [comment]
Resolved conflicts

**Comment by OhYea777** [comment]
Added 'asset_index' as a token for run configs. Currently doing Forge changes and will make a new PR to combine them

**Comment by tterrag1098** [comment]
I've verified this works properly in eclipse with the changes to my buildscript outlined in https://github.com/MinecraftForge/MinecraftForge/pull/5482

**Comment by gigaherz** [comment]
Tested in IntelliJ, works fine too. 👍

**Comment by mailboxkiller** [comment]
Cannot cast object 'LibPath' with class 'java.io.File' to class 'org.gradle.api.file.FileCollection'
trying to use: resources = project.file('resourcesDir) and 
classes = project.file('classes dir')

**Pull request merged**
